input  wire                                 S_AXI_ACLK      ,
input  wire                                 S_AXI_ARESETN   ,
output wire                                 S_AXI_AWREADY   ,
input  wire [C_S_AXI_ADDR_WIDTH-1:0]        S_AXI_AWADDR    ,
input  wire                                 S_AXI_AWVALID   ,
input  wire [ 2:0]                          S_AXI_AWPROT    ,
output wire                                 S_AXI_WREADY    ,
input  wire [C_S_AXI_DATA_WIDTH-1:0]        S_AXI_WDATA     ,
input  wire [(C_S_AXI_DATA_WIDTH/8)-1 :0]   S_AXI_WSTRB     ,
input  wire                                 S_AXI_WVALID    ,
output wire [ 1:0]                          S_AXI_BRESP     ,
output wire                                 S_AXI_BVALID    ,
input  wire                                 S_AXI_BREADY    ,
output wire                                 S_AXI_ARREADY   ,
input  wire [C_S_AXI_ADDR_WIDTH-1:0]        S_AXI_ARADDR    ,
input  wire                                 S_AXI_ARVALID   ,
input  wire [ 2:0]                          S_AXI_ARPROT    ,
output wire [ 1:0]                          S_AXI_RRESP     ,
output wire                                 S_AXI_RVALID    ,
output wire [C_S_AXI_DATA_WIDTH-1:0]        S_AXI_RDATA     ,
input  wire                                 S_AXI_RREADY    ,

//////////////////////////axi4///////////////////////////////////
